### PR TITLE
chg: dev: SDK-318: Fixing the gcp cloud configs

### PR DESCRIPTION
**Pull request by anumahadevan**
Changed some of the configs related to network, storage and location in gcp.

### CODE REVIEW

**Comment by msumit** [comment]
@anumahadevan can you fix the failing testcase.

**Comment by anumahadevan** [comment]
Sure have fixed tests and added tests for parameters added.

**Comment by msumit** [comment]
@anumahadevan is it still a valid PR?

**Comment by chattarajoy** [comment]
closing this because of no activity, please re-open if needed

**Pull request closed without merging**
