### PR TITLE
fix urllib3 import error

### PR DESCRIPTION
**Pull request by hiyer**
Fix for import error when running qds.py.

### CODE REVIEW

**Comment by jsensarma** [comment]
should we specify a urllib3 dependency in setup.py?

when i had tried out this change in my vbox - it barfed on missing urllib3.

**Comment by hiyer** [comment]
Yes, I was wondering if we need to specify the dependency somewhere. I will add this - any idea what would be a reasonable version to use (my laptop currently has 1.8.3, but PoolManager has been around since v1.0 of urllib3)?

**Comment by jsensarma** [comment]
yeah - something very low so that we don't start failing unexpectedly. v1.0 sounds fine

**Comment by mindprince** [comment]
Squash merged.

**Pull request closed without merging**
