### PR TITLE
SDK-236: Added resource class to parse it as a object

### PR DESCRIPTION
**Pull request by tanishgupta1**

### CODE REVIEW

**Comment by sourabh912** [comment]
@tanishgupta1 : Can we also write unit test ?

**Comment by tanishgupta1** [comment]
@sourabh912  I modified unit tests. Please check.

**Comment by adityaka** [comment]
@sourabh912  - could you review and we can merge this if all seems to be good

**Comment by sourabh912** [comment]
@adityaka  @tanishgupta1 : PR looks good to me. You can go ahead and merge.

**Comment by adityaka** [comment]
Squash - merged to un-released branch closing the PR thanks @sourabh912  and @tanishgupta1

**Pull request closed without merging**
