### PR TITLE
Hbase hustler

### PR DESCRIPTION
**Pull request by vrajat**
Support for turning on hbase in a cluster.

### CODE REVIEW

**Comment by mindprince** [comment]
Looks good to me. Is the API support already out for this?

**Comment by vrajat** [comment]
Yes. Hbase is alpha . So as a product it's unusable.

**Comment by vrajat** [comment]
Ping. Gentle Reminder. Can you merge this PR ?

**Comment by mindprince** [comment]
Squash merged.

**Comment by mindprince** [comment]
@vrajat Sorry, for realizing this a bit late, but how do we turn this flag off? So, let's say I turn HBase on for some cluster using `--use-hbase`. Now let's say I want to turn it off. What do I do?
I think we need to add something like `--no-hbase`? (There is an example of similar behavior in cluster.py. See `encrypted-ephemerals`)

**Comment by vrajat** [comment]
Is there something similar for use_hadoop and use_spark

**Comment by mindprince** [comment]
There are not in the SDK yet.

**Comment by vrajat** [comment]
Looks like I was a little to enthusiastic in wanting to test hbase - and
consequently adding it sdk. I am not the right person to decide the
conventions. If someone comes up with the conventions for use_hadoop,
use_spark etc., I can implement it. Update/PUT should just work but maybe
we should not allow it. What does it mean to turn off hadoop or hbase in a
cluster ? This should be hard to do. Anyway, this is way above me. If
required, I can delete the code until someone figures it out. (I'll use my
fork for testing).

**Comment by vrajat** [comment]
Closing this PR

**Pull request closed without merging**
