### PR TITLE
Refresh table added to SDK

### PR DESCRIPTION
**Pull request by sameerkedia**

### CODE REVIEW

**Comment by mindprince** [comment]
This is incomplete. Fails existing tests. Doesn't add any new tests. The help messages are random strings. And the purpose of the PR is also not clear. Please fix.

**Comment by sameerkedia** [comment]
Edited the help messages. Added a test for refresh table. Please see if it's correct.

**Comment by swatisinghi** [comment]
@mindprince, Sameer had changed the existing hive command option through the SDK to handle refresh table where as on the QDS UI Refresh table shows up as a separate command type in the drop down (although it is handled as a Hive command in the rails layer). So should we keep the behavior consistent with the UI and expose another refresh table command type through the SDK too (it can internally fire a hive command with the correct params). 

Please Suggest.

**Comment by harshshah87** [comment]
This looks like an old abandoned PR. If someone is working on it or ready to work on it, reopen it.

**Comment by chattarajoy** [comment]
This looks like an old abandoned PR. If someone is working on it or ready to work on it, reopen it.

**Pull request closed without merging**
