### PR TITLE
SDK-219 : DBExport command does not have option to pass Customercluster option

### PR DESCRIPTION
**Pull request by NamrataAShettar**
Added 'use_customer_cluster' and 'customer_cluster_label' options to DBExport and DBImport Commands.

### CODE REVIEW

**Comment by msumit** [comment]
@NamrataAShettar can you fix the broken unit tests and also add a couple of tests around the feature you've added.

**Comment by NamrataAShettar** [comment]
Yes,sure will fix the broken tests and add tests for the commands added.

**Comment by msumit** [comment]
@NamrataAShettar I see same test has been written twice. Also can you rebase your commits and make a single commit with proper message. See this http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by NamrataAShettar** [comment]
@msumit one of the tests is for the two options 'use_customer_cluster' and 'customer_cluster_label' being enabled in DBExport and the other is one for these two options beings enabled in DBImport Command. Will look into the rebasing the commits. Thanks for the link!

**Comment by msumit** [comment]
closing this one in lieu of 204

**Pull request closed without merging**
