### PR TITLE
Add --print-logs-live for friendly running

### PR DESCRIPTION
**Pull request by dfrankow**
It's only friendly to show someone what's happening as a long command runs.

### CODE REVIEW

**Comment by dfrankow** [comment]
The tests don't pass, but something like this seems civilized. Please consider it.

**Comment by mindprince** [comment]
Thanks @dfrankow
I agree, it is a very reasonable feature request.
I will confirm with the team if there is an API which will help us do it in a way better than downloading the complete logs again and again.

**Comment by dfrankow** [comment]
Thanks!

**Comment by harshshah87** [comment]
A PR has opened for live logging support.
https://github.com/qubole/qds-sdk-py/pull/134

Will close this one.

**Pull request closed without merging**
